import type { Metadata } from "next";
import {Noto_Sans_Thai} from 'next/font/google'
import "./globals.css";
import Navbar from "./components/Navbar";

const Noto = Noto_Sans_Thai({ subsets: ['thai','latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${Noto.className} antialiased bg-zinc-900`}
      >
        <Navbar/>
        <div className=" min-h-screen">
        {children}
        </div>
      </body>
    </html>
  );
}
